### PR TITLE
Stud Style

### PR DESCRIPTION
**Pull request by trevorsandy**
Stud Logo dialogue converted to Stud Style.

Screenshot - 20_01_2021 , 13_37_34

Cheers,

### CODE REVIEW

**Comment by leozide** [comment]
Thanks, this is what I had in mind. I think it looks pretty good.

**Comment by trevorsandy** [comment]
Hi Leo,

Raymond (@rsbx) suggested a colour management update for Stud Style that I believe is an improvement on what is currently in place. You can see the details - his proposed patch and my UI proposal the enable users to manage the color settings - in [this ticket](https://github.com/trevorsandy/lpub3d/issues/497#issuecomment-764969073). 

Let me know your thoughts on implementation ?

Cheers,

**Comment by rsbx** [comment]
I'd like to see the colour management be an option for all stud styles 
(including disabled). And, of course, also from the command line.

**Comment by j6t** [comment]
When I read about "stud style", I expect that I see something fancy on the studs of bricks. Is it correct that "stud style" is about this?

I place a _Brick 2 x 2 Light Grey_ on the grid. But no matter which option I choose under _Rendering_, _Stud Style_, I see no change and studs remain flat. Do I have to install something?

**Comment by rsbx** [comment]
I had issues at first, also, but downloading the most recent 
complete.zip file from LDraw.org and point LeoCAD at in Settings -> 
General fix it for me.

**Comment by j6t** [comment]
Looks like there's a bug: When a session is started while the setting is not _Plain_, stud styles are visible. Until you switch to _Plain_: thereafter, switching to any other style does not make it visible, until you restart the session.

**Comment by j6t** [comment]
The bug is actually a bit different: issue #608.

**Comment by rsbx** [comment]
I've seen similar also but I wasn't sure how repeatable it was. 
Especially since Leo was still making changes in that area. What I've 
been doing as a work around is to stop & restart the program after 
changing styles.

**Pull request merged**
