### PR TITLE
Synthesize Technic Pneumatic Tubes

### PR DESCRIPTION
**Pull request by j6t**
Technic Pneumatic Tubes can be constructed almost the same way as Technic Flex-System Hoses. Factor out a routine that constructs tube meshs from a unit circle. Then add all Pneumatic Tubes, with and without end bulges.

### CODE REVIEW

**Comment by j6t** [comment]
I've updated the patch series to apply different winding to the outer and the inner tubes. Since I do not know how to check what the correct winding is, I have assumed that the original code had the winding of the outer tube correct.

**Comment by rsbx** [comment]
My Back Face Culling patch may be able to help checking the windings. 
There's currently an open issue with the patch.

**Comment by j6t** [comment]
@rsbx I would appreciate if you could test my patches with your patch. Just paste

 - a Technic Flex-System Hose 10L (76348.dat),
 - a Technic Pneumatic Tube 7L (14657-f1.dat), and
 - a Technic Pneumatic Tube 7L with End Bulges (14657-f2.dat)

into a new project. Things become interesting if you apply a translucent color.

**Comment by rsbx** [comment]
Johannes,

I can't until later this afternoon (east coast US) but I'll take a look 
then.

**Comment by rsbx** [comment]
@j6t If by interesting you mean that it appears that the tubes have become sectional-ized and have dividers between sections, I see that. If you meant something else, attach a picture with explanation so I know what to look for.

I'm not sure what's going on there. Particularly since I tried to disable BFC for synth parts because I didn't know how the synth code worked.

**Comment by rsbx** [comment]
@j6t here are the images with both your patch and my BFC patch applied.

This image shows that BFCulling is _not_ happening:
tube+bfc-zoom
It's zoomed in enough that part of the end is clipped by the hither clipping plane.

This image also shows that BFculling is _not_ happening but with your test reversed:
foo1
The annotations are how many surfaces that area is darkened by.

This image highlights artifacts I found:
tubes

**Comment by j6t** [comment]
Thank you very much for testing the patches. I'll comment on the marked artifacts top to bottom:

 - The segmentation is also visible without the patches in Technic Flex-System Hoses. It happens only with a translucent color and non-flat shading. I think it is an artifact of how shading interacts with translucent geometry.
 - The strange shading at the bulges is indeed caused by the patches. I guess I have to change how the bulge piece is moved into its place. There may happen some inversion that corrupts the normals recorded in the mesh.
 - The visible end piece of the Flex-System Hose probably suffers from the same problem as the end bulge of the tube. At any rate, it is also visible without the patches.

I'll have another look at the handling of the stock pieces at the end of the tubes.

**Comment by rsbx** [comment]
To bullet 2: It may very well be inverted normals since they'd then be 
too different from their neighbors for smoothing.

**Comment by j6t** [comment]
I can't get it to work. As you can see here, the end piece (71533k01.da) looks fine on its own, but when it is part of the synthesized tube (21767-f2.dat), the shading is wrong:

image

Fiddling with the signs in the matrices at lines 1100 and 1114 of `lc_synth.cpp` does not make a difference with regards to shading. I don't know what else to try.

**Comment by rsbx** [comment]
Try this:

Define LC_DEBUG_NORMALS to 1 at the top of lc_scene.cpp and recompile.

That will get you the surface normal "hairs" and see if they are all 
pointed properly. Wireframe shading can help here.

If they are NOT pointed where you think they should and want to did in 
some more, disable the normals smoothing in lc_meshloader.cpp to show 
the triangle/quad normals at each vertex. The normals smoothing happens 
in AddVertex() and AddTexturedVertex(); this gets you even more "hairs".

**Comment by j6t** [comment]
Thanks for the tip. The images clearly show that the normals are not smoothed. But the same happens on the end piece of 73590b.dat (Hose Flexible 8.5L with Tabs):

image

Normals are smoothed when the end piece is separate, but not when it is in the synthesized part.
So, this behavior is not new with these patches.

**Comment by rsbx** [comment]
It's an easy test to help determine _why_ they aren't being smoothed. If 
the normals _are_ pointed correctly, then lc_meshloader.cpp:AddVertex() 
either with Optimize set to false or without a normal. If the normals 
_are not_ pointed correctly, then that needs to be fixed first.

**Comment by leozide** [comment]
Try passing optimize = true to lcMeshLoader() in lcSynthInfo::CreateMesh

**Comment by j6t** [comment]
When you look at the screenshot above, are the normals pointed correctly? I would think so for my naive definition of "point correctly".

**Comment by rsbx** [comment]
They are on the lower parts. I don't think so for the upper parts.

**Comment by j6t** [comment]
> Try passing optimize = true to lcMeshLoader() in lcSynthInfo::CreateMesh

That does it!! 

Of course, it increases the construction time of certain synthesized pieces a lot, most notably of 33763.dat (Technic Ribbed Hose 26L). It takes almost 1sec to recompute the mesh, because it consists of many, many torus-like sub-parts. For this reason, I'm not going to make this particular change just yet. It is unrelated to this topic.

**Comment by rsbx** [comment]
AddVertex() is O(v^2) where v is the number of vertices when Optimize is 
true. So anything with a HUGE number of vertices is going to spend some 
time heating up your CPU...

**Pull request merged**
