### PR TITLE
Reduce z-fighting when translucent walls are touching opaque walls.

### PR DESCRIPTION
**Pull request by j6t**
This fixes issue #301.

### CODE REVIEW

**Comment by leozide** [comment]
I liked the previous request better but the refactor is a good idea as well. 

I think the original reason to offset the polygons was to avoid z fighting between the lines and triangles of the same part so maybe we need to have 2 levels of offset, or the lines could z fight with the triangles on translucent parts.

**Comment by j6t** [comment]
I *think* that enabling GL_POLYGON_OFFSET_FILL would not have had that effect on lines that you mention. It would have required to enable GL_POLYGON_OFFSET_LINE, because the lines are drawn with line primitives. (But I am not a GL expert.)

**Comment by leozide** [comment]
I was drawing the opaque polygons offset from the lines so they wouldn't z fight but with your change you disabled that. I've tweaked it so now we still offset them but we offset the translucent polygons more to avoid the z fighting between translucent and opaque,

Maybe I'm doing it wrong and I should be always offsetting the lines instead of having 2 different triangle offsets but I think the results are the same.

**Comment by j6t** [comment]
I see now where my patch broke the rendering. Don't know how I could miss that. Thanks for cleaning up after me.

**Pull request merged**
