### PR TITLE
Automate edge colours

### PR DESCRIPTION
**Pull request by trevorsandy**
This update suggested by Raymond (@rsbx) automatically adjusts edge lines based on brightness, contrast and a value that designates where colours tone is seen as a dark or light colour. These settings, along with the high contrast stud colours, are user adjustable from the Preferences dialogue.

Here are a few shots showing the high contrast stud style:

Automate edge colour enabled:
Screenshot - 24_01_2021 , 12_58_27

...disabled:
Screenshot - 24_01_2021 , 12_56_41

Cheers,

### CODE REVIEW

**Comment by rsbx** [comment]
Trevor,

I applied this to 03b9c7 and these are my observations:

- The controls _look_ nice
- changes do not have any effect
- changes do not stick; every time to bring up the controls the settings 
are the same
- 'Brightness' should be called 'Gamma' which is what is really is and 
is searchable.
- 'Tone' is not descriptive. The setting controls which part colors are 
considered light or dark
- 'Tone' needs a finer granularity; at least 2 or 3 decimal places

I like it the direction and look forward to it actually working and 
being officially part of LeoCAD.

**Comment by leozide** [comment]
> Trevor, I applied this to 03b9c7 and these are my observations: - The controls __look__ nice - changes do not have any effect - changes do not stick; every time to bring up the controls the settings are the same - 'Brightness' should be called 'Gamma' which it what is really __is__ and is searchable. - 'Tone' is not descriptive. The setting controls which part colors are considered light or dark - 'Tone' needs a finer granularity; at least 2 or 3 decimal places I like it the direction and look forward to it actually working and being officially part of LeoCAD.

I was going through the changes and something hit me, where in the spec does it say that the colors are linear?

**Comment by rsbx** [comment]
It doesn't; that's why the luminance of the part color is calculated and 
that is used.

**Comment by leozide** [comment]
I'm still confused by the math:

- If you're assuming that the source colors are sRGB (I always assumed too and just asked LDraw for clarification), shouldn't this be using 2.2?

float r = LC_GAMMA_ADJUST(Color.Value[0], lcGetPreferences().mPartEdgeGamma);

I think this macro should be something like LC_SRGB_TO_LINEAR and only take the first parameter since we shouldn't be changing the source gamma.

- I know the results would be the same but I think this would be more readable if the comparison was made in linear space to keep all math in linear space.

if (LC_GAMMA_APPLY(ValueLuminescence, lcGetPreferences().mPartEdgeGamma) > (lcGetPreferences().mPartColorToneIndex))

- And finally the conversion back to sRGB, where you use a custom gamma. I'm still undecided but I think it would be easier for users to understand what they are changing if we apply a brightness factor in linear space and then convert the color using 2.2 gamma to be consistent.

EdgeLuminescence = LC_GAMMA_APPLY(EdgeLuminescence, lcGetPreferences().mPartEdgeGamma);

And before you mention, I know that the shader and framebuffer math is wrong.

**Comment by rsbx** [comment]
The assumption I made about the LDraw color values is that they're "raw" 
RGB values that the programs use without adjustment on PC (type) 
systems. This assumption seemed safe given how they were created and the 
lack of clarification from LDraw.org. So I'll need to adjust them from 
the device color space to a linear one; that's GAMMA_ADJUST. W3.org used 
2.4 for the gamma value, my memory of CRT values is that it's closer to 
2.2. But it's been too long since (late 90's) since I've spent a lot of 
effort in this area and only something close is needed; ideally you'd 
get it from the display system. I do not know where Trevor got 1.8 for 
Linux & Windows.

The GAMMA_APPLY in the the light/dark test is a hack, pure and simple. I 
used it to spread out the luminance values of the darker colors to make 
selecting the light/dark cutoff a more coarse to make it easier for the 
use to get the colors classified to their liking. This was mostly 
because I wanted Dark Blueish Grey to classified as light. The gamma 
vault here doesn't matter and GAMMA_APPLY was convenient.

Once a color is classified as light (dark), the edge color luminance is 
set to the value the contrast value [0.0, 1.0] 'distance' from the color 
luminance value towards 0.0 (1.0 if dark). For documentation, a very 
high contrast is desired to make it easier to determine correct 
placement. For rendering, a moderate to low contrast value gives 
something close to what you'd see if actually built. Until you changed 
the edge line thickness preference, I was using a fractional edge 
thickness with anti-aliasing to achieve something similar. This is a 
better solution.

With the edge luminance calculated, that final step to set the color to 
a grey with edge luminance and adjust it into device color space to 
match the part colors.

That's the theory for what I did. I really have no idea what other color 
adjustment are going on in the rest of the program or in the OGL code.

People in general have a hard time working in non-linear space. That's 
why I did the contrast value as a [0, 1.0] knob in the (somewhat) 
luminance perception space. The choice of gamma value only needs to be 
close to be good enough for most people.

The light/dark classifier code is a bit of a hack but I felt that most 
(BIG assumption here) are likely to select a point in the DBG area.

I think the results are pretty good and the controls easy enough to play 
with to get something good enough. Manually selecting the edge color for 
each part color WILL yield better results for a particular situation. 
But manually selecting each edge color is tedious and multiple settings 
are desired.

Hopefully I explained it well enough. If not, let me know and I'll try 
to clarify some more.

**Comment by trevorsandy** [comment]
Hi Guys,

> - changes do not have any effect
Normally, I develop in LeoCAD and then port to LPub3D but this time I did it the other way around. It seems to be working in LP3D. For LeoCAD, I expect there will be changes so I just wanted to get something out quickly. It is likely the changes are not being saved to preferences, I ll take a look.

> - changes do not stick; every time to bring up the controls the settings are the same
Same as above. I think I forgot to port the block that update the settings back to Profile settings.

> - 'Brightness' should be called 'Gamma' which it what is really __is__ and is searchable.
Indeed; however, my approach to UI is more “by an engineer for general users” than “by an engineer for engineers”. Having said that, it is trivial to change the label in the dialogue to say what you prefer.

> - 'Tone' is not descriptive. The setting controls which part colors are considered light or dark.
This is clearly stated in the tooltip. Tone summarises which aspect of the colour is used to determine if it is light or dark. I call the setting an “index”.

> - 'Tone' needs a finer granularity; at least 2 or 3 decimal places
These settings are all floats. Are you saying you would like to see the displayed value to 3 decimal places ? Or are you saying the user should be able to precise the value to 3 decimal places ? For the latter, a spinner would be needed in place of the current slider.

Cheers,

**Comment by rsbx** [comment]
* Noted. I was stating my observations even though I knew the code was 
primarily for Leo. Mostly because I'm interested in this capability and 
I had a hand in it. :-)

* My thinking on GAMMA is that calling it "Brightness" is misleading and 
encourages expectation that will not be met. Most people should not need 
to adjust it if the default is close enough to that of their display.

* I had no idea what "Tone" meant until I read the tool-tip; hence my 
comment. I do not have a good suggestion but think "Index" is better. 
Maybe "L/D Index" and hope people find/read the tool-tip?

* With the slider I was not able to get it to land on 0.39 which is what 
I was attempting to do since there is not much space between colors in 
that area. This is likely a control that people will like to adjust to 
their preference; possibly even depending on the current model.

**Comment by trevorsandy** [comment]
I've cleaned up the code and treated the reported issues.

- Set the default Gamma to 2.20
- Changed Tone to Value L/D
- Contrast, Gamma, and Value L/D set to increment and display at the hundredth place (2 decimals) - use L/R arrow keys to precise your selection
- Stud Style Black colour set to Preferences/Profile value versus hard-coded default
- Selections persist to preferences and are applied on dialogue accept

Screenshot - 25_01_2021 , 08_30_48

Cheers,

**Comment by trevorsandy** [comment]
This update goes a bit further to make the high contrast colours configurable and splits the colour preferences dialogue.

High contrast settings.
Screenshot - 25_01_2021 , 13_29_59

Autoamate edge colour settings
Screenshot - 25_01_2021 , 13_29_32

Cheers,

**Comment by rsbx** [comment]
Great! I'll try this later today.

**Comment by rsbx** [comment]
After looking at the latest, these are my comments/observations:

- I like this capability a lot
- Consider replacing the text "Value L/D Index" with "L/D Value" or "Light/Dark Value"
- Gamma should default to 2.2. Might want to just make it a constant since part colors aren't adjustable.
- Consider a button in each sub-preference to restore the defaults or the last saved so users can safely experiment
- "Dark Parts Edge Color" appeared to have no effect (tried on a Black part)
- What is the ellipsis button in "High Contrast Studs" sub-preference for? Clicking it appear to do nothing.
- I'd like these control settings available from the CLI, also, since I'm using LeoCAD as an external renderer as well as for model design

**Comment by trevorsandy** [comment]
> I like this capability a lot

Me too.

> Consider replacing the text "Value L/D Index" with "L/D Value" or "Light/Dark Value"

Done.

> Gamma should default to 2.2. Might want to just make it a constant since part colors aren't adjustable.

Done.

> Consider a button in each sub-preference to restore the defaults or the last saved so users can safely experiment

Done.

> "Dark Parts Edge Color" appeared to have no effect (tried on a Black part)

This will only work if Automate edge color is disabled. At some point, It might be helpful to either disable when Automate edge color is enabled or set a notice in the tooltip.

> What is the ellipsis button in "High Contrast Studs" sub-preference for? Clicking it appear to do nothing.

Reset the colours - the wrong button was assigned so signals were not received. This behaviour has been corrected.

> I'd like these control settings available from the CLI, also, since I'm using LeoCAD as an external renderer as well as for model design

I'll want to enable for LP3D CLI also so it should be available soon - cooking some other things at the moment.

Colours in action:
Screenshot - 25_01_2021 , 21_22_18

New reset buttons:
Screenshot - 25_01_2021 , 21_42_34

Cheers,

**Comment by rsbx** [comment]
That first image is scary!

The following is based on your message and images; I have not actually 
tested the latest patches yet.

It looks like you have a reset for each control. That may overkill; a 
reset for all the controls of a preference window would likely be 
sufficient.

I thought I tested "Dark Parts Edge Color" with Auto edge color off and 
didn't see any effect. I'll test again.

My comment on the CLI was so that you and Leo __thought__ about the 
issue since it impacts code that's already had issues.

WARNING! Random musing follows:
The auto edge color preferences are controls, and also edge thickness 
and LOD, that would benefit from being "live". That is, when the control 
is changed, the view & parts list change, in real time, to reflect the 
new control values. Is that even possible?

**Comment by rsbx** [comment]
@trevorsandy 

I'm trying you latest patches:

- I'm not seeing "Dark Parts Edge Color" applied
- "Stud Edge Color" is being applied to all edges, not just the stud edges
- Automatic edge color is off
img

**Comment by trevorsandy** [comment]
This is working for me.

Steps:
- Open pyramid.mpd
- From the colour tab, drag dark brown (308) to a brick
- Open the high contrast submenu and select a replacement dark parts edge colour
- Close the high contrast submenu and the preferences dialogue
- The selected colour should appear on the dark part.

Screenshot - 25_01_2021 , 23_15_00

Cheers,

**Comment by rsbx** [comment]
The issue appears to be what constitutes a dark part. I was testing with Redish Brown; when I use Dark Brown, works.

**Comment by leozide** [comment]
Thanks for the changes.

**Pull request merged**
