### PR TITLE
Add snap installation instructions and improve the readme.md formatting.

### PR DESCRIPTION
**Pull request by aromatic-dev**
- Added snap installation instructions
- Formatted the markdown file better
- Renamed README.txt to README.md to allow it to render as markdown when viewed

### CODE REVIEW

**Comment by j6t** [comment]
Would it be possible to squash the "Fix build" commit into the "Rename README" commit, please? After all, it is about the same topic, and just the answer to "Ooops, I made a mistake earlier". Not something that we need in the project history when it can be avoided easily.

**Comment by aromatic-dev** [comment]
> 
> 
> Would it be possible to squash the "Fix build" commit into the "Rename README" commit, please? After all, it is about the same topic, and just the answer to "Ooops, I made a mistake earlier". Not something that we need in the project history when it can be avoided easily.

Done, I thought it would be an option at the time of merging the PR.

**Comment by j6t** [comment]
Actually, did not mean that you squash *all* patches together into a single one, just the "Rename" and the "Oops, that broke the build" one. The other one with new instructions was a different topic and should go into its own patch. So, if you ask me, this iteration is even worse than the earlier iteration.

That said, I am not the maintainer of this project, but I'm just venting may thoughts on what a good patch set should look like. It is on @leozide to decide. I apologize that I caused more work for everyone.

**Comment by aromatic-dev** [comment]
> 
> 
> Actually, did not mean that you squash _all_ patches together into a single one, just the "Rename" and the "Oops, that broke the build" one. The other one with new instructions was a different topic and should go into its own patch. So, if you ask me, this iteration is even worse than the earlier iteration.
> 
> That said, I am not the maintainer of this project, but I'm just venting may thoughts on what a good patch set should look like. It is on @leozide to decide. I apologize that I caused more work for everyone.

All good -- I don't think having two separate commits for this PR adds any value. Let's wait on @leozide.

**Comment by leozide** [comment]
I don't mind either way.

I'll keep the .txt extension on Windows since it doesn't have a default reader.

**Pull request merged**
