### PR TITLE
Fix #102: don't force using unencrypted traffic

### LINKED ISSUE #102: www.leocad.org website serves content over plain HTTP
Steps to reproduce:
1. Go to http://www.leocad.org

Expected results:
* Get redirected to https://www.leocad.org

Actual results:
* Content is served over plain HTTP

Additionally, forcing HTTPS by visiting https://www.leocad.org reports:

```
www.leocad.org uses an invalid security certificate.

The certificate is only valid for the following names: www.github.com, *.github.com, github.com,
*.github.io, github.io, *.githubusercontent.com, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by leozide** [comment]
I'm pretty sure this breaks the custom domain, let me see if github support has something to disable redirects.

**Comment by leozide** [comment]
Hi Leonardo,

Thanks for contacting GitHub Support!

I'm afraid HTTPS (SSL) support isn't currently available for GitHub Pages sites with custom domains, nor is it possible to use a custom domain and .github.io address simultaneously. One alternative that some users have reported success with is CloudFlare:

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

Please bear in mind that we don't provide support for that approach, so if you do decide to explore it you'll need to contact CloudFlare for assistance with any difficulties you have.

That said, we're always looking to make GitHub better, and this is definitely something on our radar. While I can't make any guarantees, I've added your +1 to this suggestion on our internal Feature Request List.

**Comment by janisozaur** [comment]
thanks a lot for providing that information.

feel free to close this PR then or keep it open if you want it to use for tracking.

**Comment by leozide** [comment]
GH now supports https for custom domains

**Pull request closed without merging**
