### PR TITLE
Upgrade the project so it could be compatible to Qt 5.7

### PR DESCRIPTION
**Pull request by mhoangvslev**
Hi,

I wrote you few message via email (from minhhoangdang@hotmail.com) but you didn't reply.
I compiled the project with Visual Studio and I am not able to see changes:
- The preview images in Brick Browser are not active.
- Whenever I drop a brick it crashes.

Here are some features that might interest you:
- Low poly bricks support: remove real-life details out of models. I can help make new parts.
- FBX export
- UV Texture on bricks model so people can apply custom design (decals)

### CODE REVIEW

**Comment by leozide** [comment]
You need to switch to the new parts toolbar, it sounds like you're still using the old one.

There's a limited LOD system that can be expanded to do more.
I considered FBX in the past but the SDK isn't very nice and I think obj/3ds cover all 3d packages out there.
There's support for textures using the TEXMAP extension but no official parts use it.

**Comment by leozide** [comment]
Regarding the pull:
Which platform are you compiling? I've been using Qt 5.7 without problems, and I'm pretty sure some of those changes will break some platforms (adding common/lc_global.h and removing the DEPRECATED define).

**Comment by mhoangvslev** [comment]
Here is what I did:
- Install Qt 5.7
- Clone the project
- Use qmake -tp vc to make VS2015 project.
- Compile and saw errors which I fixed using those changes.

**Comment by leozide** [comment]
This breaks Linux, I think the correct thing is to use:
INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtZlib

**Comment by leozide** [comment]
Can you try 77efda9 please? I think that's all that needs to be done and it doesn't break the other platforms.

I'm just not sure why you need to add the DISABLE_DEPRECATE define, I can test it if you're getting errors without.

The warning about lc_global.h when generating the vcproj doesn't seem to matter, and gcc doesn't like it changed so I'd rather not change this part.

**Comment by mhoangvslev** [comment]
Tested, it is really good.
However, still need to add prefix "common/" in some file. Making new pull request

**Pull request closed without merging**
