### PR TITLE
Add GPL-2.0 license file for Github

### PR DESCRIPTION
**Pull request by saxbophone**
Project already is licensed as GPL-2.0, adding this file just makes this clear to users exploring the source via Github and Github will pick up on this, displaying a "GPL-2.0" badge on the project stats sidebar:

image

This is really useful to allow other developers to see what license the code is released under at a glance rather than have to hunt the information down.

Related to #78

### CODE REVIEW

**Comment by inson1** [comment]
@leozide Why it wasnt merged?

**Comment by saxbophone** [comment]
> @leozide Why it wasnt merged?

I (the author) closed it because it seemed clear to me that the project maintainer wasn't interested in accepting it, alas.

I can reöpen it if you want but I'm somehow doubtful that it will go anywhere...

**Comment by inson1** [comment]
@saxbophone yes, I get it. That is why I'm asking the maintainer. :)

**Comment by nathaneltitane** [comment]
he's either submerged with other occupations or doesn't see it as a priority ?!

**Comment by felipesanches** [comment]
@leozide, this is straightforward, useful and, to be honest, legally relevant (for the best clarity of the licensing status of the project). It is also the canonical way of declaring licensing. I suggest you merge this as is.

**Comment by felipesanches** [comment]
I also noticed that the repo does have a license file, but it is located in the `docs/` directory, which is unconventional. GitHub, for instance, does not detect it due to its unusual location.

@saxbophone, please fix your contribution to actually substitute the license file from `docs/` with a file at the root of the repo. (and ideally please also git-squash everything into a single commit, to keep the git history clean)

**Comment by felipesanches** [comment]
@saxbophone and/or @leozide, you can cherry-pick from https://github.com/felipesanches/leocad/commit/43aacbf688930de50de957bf2f6b8f7869d3ed8b

**Comment by saxbophone** [comment]
Thank you for your response. It's useful to know that there's already a
copy of the license in the docs directory. I wonder if there is a config
option that can be placed in a file in the .github directory to tell github
to use this existing file in the docs directory for license detection?

Thanks for inviting me to contribute further, sadly I will have to decline
on this occasion. The lack of movement on the issue suggests it would not
be a good use of my time, please feel free to integrate any existing work
I've done yourself or close this ticket as you see fit.

Cheers

**Comment by felipesanches** [comment]
It is sad to see contributors giving up due to lack of activity in the repo.

For that reason, I am starting to work on a friendly-fork of this repo, in which I am gradually cherry-picking (and sometimes refactoring) the contributions that I consider to be good, from all the open PRs. I hope that @leozide will also merge them. And hopefully I can help him to further improve LeoCAD together.

My repo is at https://github.com/felipesanches/leocad and I am keeping my **master** branch identical to leozide's, while I am adding more commits on my **main** branch.

**Comment by saxbophone** [comment]
> It is sad to see contributors giving up due to lack of activity in the repo.
> 
> For that reason, I am starting to work on a friendly-fork of this repo, in which I am gradually cherry-picking (and sometimes refactoring) the contributions that I consider to be good, from all the open PRs. I hope that @leozide will also merge them. And hopefully I can help him to further improve LeoCAD together.

Bless you @felipesanches . I wish you well.

**Pull request closed without merging**
