### PR TITLE
Travis CI: linuxdeployqt version update

### PR DESCRIPTION
**Pull request by pbartfai**
version 3 is not available any more

### CODE REVIEW

**Comment by leozide** [comment]
Thanks, I've been meaning to fix this. Ideally I'd like to upload the builds from commits with tags to github directly so it's available on the downloads page. Do you know how to do that?

**Comment by Symbian9** [comment]
@leozide, maybe its better upload to OBS, like @pbartfai already did?

* http://download.opensuse.org/repositories/home:/pbartfai/

@pbartfai, could you update you OBS system for daily/nightly builds of LeoCAD? Also, it would be cool if you also can produce AppImage's for LeoCAD (for 16.04 LTS)

* http://download.opensuse.org/repositories/home:/pbartfai/AppImage/

**Comment by pbartfai** [comment]
Please check [https://docs.travis-ci.com/user/deployment/releases/](https://docs.travis-ci.com/user/deployment/releases/)

**Comment by Symbian9** [comment]
@pbartfai, could you trigger your OBS for build LeoCAD from 'master', please? (because you still use 0.83.x)
* http://download.opensuse.org/repositories/home:/pbartfai/xUbuntu_16.04/amd64/

**Comment by pbartfai** [comment]
Debian version string updated. Please update version string in leocad.spec

**Comment by Symbian9** [comment]
> Please update version string in leocad.spec

Added as pull request
* https://github.com/leozide/leocad/pull/66

**Pull request merged**
