### PR TITLE
Issue #626 - Update ldraw.xml to version 2021-01-16

### PR DESCRIPTION
**Pull request by hfiguiere**
This solve the issues with the files in #626.

From https://gitlab.com/sylvainls/lxf2ldr/-/blob/master/common/ldraw.xml

### CODE REVIEW

**Comment by hfiguiere** [comment]
Or maybe you expect the user to install it next to the `library.bin`? (seems the code look for it there)

**Comment by leozide** [comment]
Unfortunately I can't take this change, the author doesn't allow me to include his files in LeoCAD. If you look at the history in https://github.com/leozide/leocad/commits/master/resources/ldraw.xml you'll see that I tried to include it in the past and later remove it.

**Comment by hfiguiere** [comment]
From https://gitlab.com/sylvainls/lxf2ldr/-/blob/master/README.md

> (ldraw.xml never had any explicit license and has been treated as “free to use and modify,” so I guess is Public Domain or CC0.

So I assumed this was ok. 

The commit history doesn't really explain why added / removed.

**Comment by leozide** [comment]
Ok, I included some code from his project in the past but this time it's just the xml so I think it's ok.

**Pull request merged**
