### PR TITLE
Blender and POVRay Lights

### PR DESCRIPTION
**Pull request by trevorsandy**
This PR Supersedes Blender Lights #870.

The following items have been added.

- POVRay lights
- Detect and use LGEO library parts if available

The following items have been updated.

- Ported commit 7688500f80e35fbddda9e05418abb3810a75d5a3 from PR #870
- Drawn directional light interface
- Drawn area light interface
- POVRay pov file generation 
- Select between POVRay and Blender lights from light properties

POVRay directionallight
POVRay Directionallight

POVRay render  before update
01_POVRay-Before-Update

POVRay render  after update
02_POVRay-After-Update

POVRay render  using LGEO library
03_POVRay-LGEO-Update

Light meta commands:

- Pointlight
    - Blender
        ```
        0 !LEOCAD LIGHT POSITION -220.502 -342.227 212.352
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT DIFFUSE 1
        0 !LEOCAD LIGHT SPECULAR 1
        0 !LEOCAD LIGHT POWER 1
        0 !LEOCAD LIGHT RADIUS 0.25
        0 !LEOCAD LIGHT TYPE POINT NAME Pointlight 1
        ```
    - POVRay
        ```
        0 !LEOCAD LIGHT POV_RAY
        0 !LEOCAD LIGHT POSITION -220.502 -342.227 212.352
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT POWER 1
        0 !LEOCAD LIGHT TYPE POINT NAME Pointlight 1
        ```
- Spotlight
    - Blender
        ```
        0 !LEOCAD LIGHT POSITION -83.6297 274.359 212.352
        0 !LEOCAD LIGHT TARGET_POSITION -6.39438 99.0089 71.713
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT DIFFUSE 1
        0 !LEOCAD LIGHT SPECULAR 1
        0 !LEOCAD LIGHT POWER 10
        0 !LEOCAD LIGHT SPOT_SIZE 75
        0 !LEOCAD LIGHT RADIUS 0.25
        0 !LEOCAD LIGHT SPOT_BLEND 0.15
        0 !LEOCAD LIGHT TYPE SPOT NAME Spotlight 1
        ```
    - POVRay
        ```
        0 !LEOCAD LIGHT POV_RAY
        0 !LEOCAD LIGHT POSITION -83.6297 274.359 212.352
        0 !LEOCAD LIGHT TARGET_POSITION -6.39438 99.0089 71.713
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT POWER 1
        0 !LEOCAD LIGHT RADIUS 30
        0 !LEOCAD LIGHT SPOT_FALLOFF 45
        0 !LEOCAD LIGHT SPOT_TIGHTNESS 0
        0 !LEOCAD LIGHT TYPE SPOT NAME Spotlight 1
        ```
- Directionallight
    - Blender
        ```
        0 !LEOCAD LIGHT POSITION -165.259 -228.058 201.597
        0 !LEOCAD LIGHT TARGET_POSITION 3.0868 -31.0625 93.5714
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT DIFFUSE 1
        0 !LEOCAD LIGHT SPECULAR 1
        0 !LEOCAD LIGHT STRENGTH 10
        0 !LEOCAD LIGHT ANGLE 11.4
        0 !LEOCAD LIGHT TYPE DIRECTIONAL NAME Directionallight 1
        ```
    - POVRay
        ```
        0 !LEOCAD LIGHT POV_RAY
        0 !LEOCAD LIGHT POSITION -165.259 -228.058 201.597
        0 !LEOCAD LIGHT TARGET_POSITION 3.0868 -31.0625 93.5714
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT STRENGTH 1
        0 !LEOCAD LIGHT TYPE DIRECTIONAL NAME Directionallight 1
        ```
- Arealight
    - Blender
        ```
        0 !LEOCAD LIGHT POSITION 276.369 -209.876 221.864
        0 !LEOCAD LIGHT TARGET_POSITION -1.0092 -62.8147 49.4116
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT DIFFUSE 1
        0 !LEOCAD LIGHT SPECULAR 1
        0 !LEOCAD LIGHT POWER 10
        0 !LEOCAD LIGHT WIDTH 0.25 HEIGHT 0.25
        0 !LEOCAD LIGHT SHAPE SQUARE
        0 !LEOCAD LIGHT TYPE AREA NAME Arealight 1
        ```
    - POVRay
        ```
        0 !LEOCAD LIGHT POV_RAY
        0 !LEOCAD LIGHT POSITION 276.369 -209.876 221.864
        0 !LEOCAD LIGHT TARGET_POSITION -1.0092 -62.8147 49.4116
        0 !LEOCAD LIGHT COLOR_RGB 1 1 1
        0 !LEOCAD LIGHT POWER 1
        0 !LEOCAD LIGHT AREA_ROWS 10 AREA_COLUMNS 10
        0 !LEOCAD LIGHT WIDTH 200 HEIGHT 200
        0 !LEOCAD LIGHT SHAPE SQUARE
        0 !LEOCAD LIGHT TYPE AREA NAME Arealight 1
        ```

- POVRay light meta command to select POVRay format - default format is Blender
   ```
   0 !LEOCAD LIGHT POV_RAY
   ```

- POVRay light meta command to turn off shadows
   ```
   0 !LEOCAD LIGHT SHADOWLESS
   ```

POVRay pov file generation meta commands
```
    0 !LEOCAD POV_RAY HEADER_INCLUDE_FILE <string>
    0 !LEOCAD POV_RAY FOOTER_INCLUDE_FILE <string>
    0 !LEOCAD POV_RAY EXCLUDE_FLOOR
    0 !LEOCAD POV_RAY EXCLUDE_BACKGROUND
    0 !LEOCAD POV_RAY FLOOR_AXIS <string> x|y|z - default is y
    0 !LEOCAD POV_RAY FLOOR_COLOR_RGB <r,g,b> in 0.0f-1.0f format
    0 !LEOCAD POV_RAY FLOOR_AMBIENT <float>
    0 !LEOCAD POV_RAY FLOOR_DIFFUSE <float>
    0 !LEOCAD POV_RAY NO_REFLECTION
    0 !LEOCAD POV_RAY NO_SHADOW
    0 !LEOCAD POV_RAY USE_LGEO
```

Cheers,

### CODE REVIEW

**Comment by leozide** [comment]
Hi Trevor, I've been using your branch to finish developing lights, I'll merge it when it's finished.

**Comment by trevorsandy** [comment]
Hello Leo, Thanks for the update. 

Indeed, the new light features will be great for hi-def renders.

Let me know when you've finalized the exported/saved Blender light attributes and I'll  update the [Blender addon](https://github.com/trevorsandy/blenderldrawrender).

Cheers,

**Comment by leozide** [comment]
I think I fixed it correctly now, the vectors should be x * size and I added the grid properties back.

**Comment by leozide** [comment]
Hi Trevor, I think I finished going through all the settings, what do you think about them now?

**Pull request merged**
