### PR TITLE
3D Preview

### PR DESCRIPTION
**Pull request by trevorsandy**
Hi Leo - Here's a preview widget that displays parts from the part selection tab that allows camera rotation/orbiting, panning and window resizing. It is launched, with the selected part, by double clicking a part icon in the selection window.

Screenshot - 22_09_2020 , 04_10_31

It appears to work as expected on LPub3D but on integration with LeoCAD, there is an index issue at the lcLibrary::Unload() routine on application close. I imagine there must be some dangling item on closing the preview window that is not detected until cleanup at application close. However, I haven't been able to track it down.

image

Refactored the code a bit and added 'Dockable' option - available in Preferences. Also enabled on timeline - just as with part selection icons, double-click a timeline node to launch.

Still haven't tracked down the cause of the abend on close. It looks like the library Unload routine is trying to delete [a part at] the same address twice but I haven't found the offending code.

image

Cheers,

### CODE REVIEW

**Comment by leozide** [comment]
Thanks Trevor, pretty cool feature. I've merged into a branch and I'll fix a couple of minor things (like the crash you mentioned) before I add it.

**Comment by trevorsandy** [comment]
The Preview display is now enabled on Properties. Updates are triggered on Properties' setPiece call (when a piece takes focus) and slotSetValue call (when the piece combo drop-down current index changes). As this new behaviour is automatic, I've added a preview toolbar button that 'locks' the priview to disable updates so the user can keep a specific piece (i.e. submodel) in the priview. Notice in the shot below a 1x 2 plate is selected but the left wing submodel is displayed. The 'lock/unlock' toolbar button icon, tooltip and status, is set to indicate the lock/unlock state. Lastly, updates from Properties are only triggered when the Preview display position is set to 'Dockable'.

For refactoring - because the same 'set location' code block is used for part selection, properties and timeline, I moved it to lcQGLWidget::setPreviewPosition(const QRect& ParentRect). 

Screenshot - 07_10_2020 , 15_15_21

Cheers,

**Comment by leozide** [comment]
Can you resend this? I don't know how this got closed and I can't merge.

**Comment by trevorsandy** [comment]
Done - see #511 
 
Cheers,

**Pull request closed without merging**
