### PR TITLE
Support small linear actuators; handle move large actuators and a new universal joint.

### PR DESCRIPTION
**Pull request by j6t**
The LDraw 2019-03 library update had a few changes in pieces
that can be synthesized. Make them work.

### CODE REVIEW

**Comment by leozide** [comment]
Thanks for the fixes

**Comment by Symbian9** [comment]
What about replace linear actuator (placed relatively at `X=0;Y=30;Z=0`) with rotate actuator (placed relatively at `X=0;Y=0;Z=0`)

Or add rotate actuators to already added linear (like in flexible parts)?

pic.1

**Comment by j6t** [comment]
I'm sorry, I do not understand. The image shows a flexible axle and a universal joint. Do you see a problem somewhere? Or are you suggesting a new feature?

And what is a rotate actuator?

**Comment by Symbian9** [comment]
> The image shows a flexible axle and a universal join

I just use flexible axle to show "actuator" with *linear move* & *rotate* handles, where this actuator placed at the center of part.

Then I could select any additional part (on image above its axle part) and rotate it according actuator rotating.

With actual joint part actuator I can't rotate additional parts in same angle as joint sub-part ("end") rotated.

pic.2

> Or are you suggesting a new feature?

I suggest that joint parts actuator should has linear and/or rotate actuator for be able rotate sub-part ("end").

**Comment by j6t** [comment]
If you want to rotate a universal joint, you have to rotate it at is regular handle, and then adjust the position of the green handle. There is no degree of freedom; extra rotation is not possible.

For linear actuators, you are right that it could make sense to provide a possibility to rotate the piston.

The shock absorbers can probably also be twisted so that the two ends are not aligned.

Braided strings have end parts that can already be rotated as necessary by its corresponding handle.

All other synthesized parts either do not have any rotational freedom (e.g., flexible axles) or are rotationally symmetric and do not need a rotation (if it is not already there).

**Comment by Symbian9** [comment]
> If you want to rotate a universal joint

No. I want rotate joint "end" to specified angle using actuator placed at the center of joint axis' cross point.

There is small hack how to rotate actuator and selected additional part (for example axle part), but it not applied to the joint "end".

pic.3

**Comment by j6t** [comment]
The control point of the universal joint is not intended to be used like this.

Usually, you do not have any freedom where to place the axle. That is you have placed and rotated it first. Then the adjustment of the universal joint is just a matter of placing the control point at the same X/Y/Z that the axle has.

**Pull request merged**
